default_language_version:
  python: python3

default_stages: [commit, push]

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.5.0
    hooks:
      - id: trailing-whitespace
      - id: check-json
      - id: check-yaml
      - id: end-of-file-fixer
        exclude: LICENSE

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.9.9
    hooks:
      - id: ruff-format
      - id: ruff-check
