name: Preflight
on:
  push:
    branches: [master]
  pull_request:

jobs:
  preflight:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - uses: astral-sh/setup-uv@v5
      - name: Run preflight script
        run: ./scripts/preflight.sh
